source 'https://rubygems.org'

# For development while Lanes is evolving track master branch
gem "lanes",   github: 'argosity/lanes',   branch: 'master'

# gem "lanes", '0.1.9'

gem "rake"
gem 'puma'
