source 'https://rubygems.org'

# For development while Hippo is evolving track master branch
gem "hippo-fw", git: "https://github.com/argosity/hippo", branch: 'master'

# gem "hippo", '0.9.9'

gem "rake"
gem 'puma'
