source 'https://rubygems.org'

# For development while Lanes is evolving track master branch
gem "lanes", git: "https://github.com/argosity/lanes", branch: 'master'

# gem "lanes", '<%= Lanes::VERSION %>'

gem "rake"
gem 'puma'
